=== Novia-RDI-Seafaring/auto-param-extraction/data/example/01_datasheet_table_simple_0_87bc95828b8e303cf4ddb569fd10ba485037193bb8c22c0ab22522e7aae58896/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "JSON schema defining the parameters that are do be extracted from a datasheet.",
    "definitions": {
        "bboxes": {
            "description": "List of Bounding boxes (xyxy notation) outlining the information in the original document required to extract the parameter. If the parameter is explicitly stated this list usually contains only 1 bbox. If information from multiple location needs to be combined, it contains the bbox to each of those locations.",
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 4,
                "maxItems": 4
            },
            "minItems": 1
        },
        "pageIndexes": {
            "description": "Index of the pages required to extract the specific parameter. Can be multiple pages if information is distributed across pages.",
            "type": "array",
            "items": {
                "type": "integer"
            },
            "minItems": 1
        },
        "parameter_properties": {
            "type": "object",
            "properties": {
                "value": {
                    "description": "Value of the parameter",
                    "type": [
                        "number",
                        "string"
                    ]
                },
                "unit": {
                    "description": "Unit of the parameter. For unitless parameters this can be null.",
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "bboxes": {
                    "$ref": "#/definitions/bboxes"
                },
                "pageIndexes": {
                    "$ref": "#/definitions/pageIndexes"
                }
            },
            "additionalProperties": false,
            "required": [
                "value",
                "unit",
                "bboxes",
                "pageIndexes"
            ]
        }
    },
    "type": "object",
    "properties": {
        "FullHeightAD": {
            "label": "FullHeightAD",
            "description": "Full height of the heat exchanger of frame type AD. Desired unit: mm.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "FullWidthAD": {
            "label": "FullWidthAD",
            "description": "Full width of the heat exchanger of frame type AD. Desired unit: mm.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "FullHeightALB": {
            "label": "FullHeightALB",
            "description": "Full height of the heat exchanger of frame type ALB. Desired unit: mm.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "FullWidthALB": {
            "label": "FullWidthALB",
            "description": "Full width of the heat exchanger of frame type ALB. Desired unit: mm.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "FramePlateMaterial": {
            "label": "FramePlateMaterial",
            "description": "Material of frame plate. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "FieldGasketsMaterial": {
            "label": "FieldGasketsMaterial",
            "description": "Material of the field gaskets. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "ADPEDMaxDesignPressure": {
            "label": "ADPEDMaxDesignPressure",
            "description": "Max design pressure for frame type AD with PED. Desired unit: bar.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "ADpvcALSMaxDesignPressure": {
            "label": "ADpvcALSMaxDesignPressure",
            "description": "Max design pressure for frame type AD with pvcALS. Desired unit: bar.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "EGpvcALSMaxDesignPressure": {
            "label": "EGpvcALSMaxDesignPressure",
            "description": "Max design pressure for frame type EG with pvcALS. Desired unit: bar.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "EGASMEMaxDesignTemp": {
            "label": "EGASMEMaxDesignTemp",
            "description": "Max temerature for frame type EG with ASME. Desired unit: °C.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "EGPEDMaxDesignTemp": {
            "label": "EGPEDMaxDesignTemp",
            "description": "Max temerature for frame type EG with PED. Desired unit: °C.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "HeatTransferPlatesMaterial": {
            "label": "HeatTransferPlatesMaterial",
            "description": "Material of heat transfer plates. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "MetalLinedFlangeConnectionMaterial": {
            "label": "MetalLinedFlangeConnectionMaterial",
            "description": "Material of metal ligned flange connections. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "RubberLinedFlangeConnectionMaterial": {
            "label": "RubberLinedFlangeConnectionMaterial",
            "description": "Material of rubber ligned flange connections. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "ADpvcALSFlangeConnectionStandard": {
            "label": "ADpvcALSFlangeConnectionStandard",
            "description": "Flange Connection standard for frame type AD with pvcALS. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "ADPEDFlangeConnectionStandard": {
            "label": "ADPEDFlangeConnectionStandard",
            "description": "Flange Connection standard for frame type AD with PED. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        },
        "EGASMEFlangeConnectionStandard": {
            "label": "EGASMEFlangeConnectionStandard",
            "description": "Flange Connection standard for frame type EG with ASME. Desired unit: None.",
            "type": "object",
            "properties": {
                "parameter_properties": {
                    "$ref": "#/definitions/parameter_properties"
                }
            },
            "additionalProperties": false,
            "required": [
                "parameter_properties"
            ]
        }
    },
    "additionalProperties": false
}

=== Novia-RDI-Seafaring/auto-param-extraction/data/example/01_datasheet_table_simple_1_a1903161d48c3ced6e38e715e922f42e0826f9ba3414c04e377026a70c642941/gt_value.json
{
    "FullHeightAD": {
        "parameter_properties": {
            "value": 850,
            "unit": "mm",
            "bboxes": [
                [
                    162.51,
                    50.849763779527734,
                    301.09000000000003,
                    73.32976377952775
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "FullWidthAD": {
        "parameter_properties": {
            "value": 420,
            "unit": "mm",
            "bboxes": [
                [
                    301.09,
                    50.849763779527734,
                    439.66999999999996,
                    73.32976377952775
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "FullHeightALB": {
        "parameter_properties": {
            "value": 900,
            "unit": "mm",
            "bboxes": [
                [
                    162.51,
                    95.8897637795277,
                    301.09000000000003,
                    118.36976377952772
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "FullWidthALB": {
        "parameter_properties": {
            "value": 412,
            "unit": "mm",
            "bboxes": [
                [
                    301.09,
                    95.8897637795277,
                    439.66999999999996,
                    118.36976377952772
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "FramePlateMaterial": {
        "parameter_properties": {
            "value": "Carbon steel, epoxy painted",
            "unit": null,
            "bboxes": [
                [
                    200.61,
                    352.4097637795277,
                    566.94,
                    374.8897637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "FieldGasketsMaterial": {
        "parameter_properties": {
            "value": "CGB, XGBL",
            "unit": null,
            "bboxes": [
                [
                    200.61,
                    307.3697637795277,
                    566.94,
                    329.84976377952773
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "ADPEDMaxDesignPressure": {
        "parameter_properties": {
            "value": 9.0,
            "unit": "bar",
            "bboxes": [
                [
                    124.29,
                    464.9697637795277,
                    337.1,
                    487.4497637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "ADpvcALSMaxDesignPressure": {
        "parameter_properties": {
            "value": 9.5,
            "unit": "bar",
            "bboxes": [
                [
                    124.29,
                    487.4497637795277,
                    337.1,
                    509.9297637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "EGpvcALSMaxDesignPressure": {
        "parameter_properties": {
            "value": 11.5,
            "unit": "bar",
            "bboxes": [
                [
                    124.29,
                    509.92976377952766,
                    337.1,
                    532.4097637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "EGASMEMaxDesignTemp": {
        "parameter_properties": {
            "value": 240,
            "unit": "°C",
            "bboxes": [
                [
                    337.1,
                    532.4897637795277,
                    566.94,
                    554.9697637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "EGPEDMaxDesignTemp": {
        "parameter_properties": {
            "value": 180,
            "unit": "°C",
            "bboxes": [
                [
                    337.1,
                    554.9697637795277,
                    566.94,
                    577.4497637795278
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "HeatTransferPlatesMaterial": {
        "parameter_properties": {
            "value": "201/202L",
            "unit": null,
            "bboxes": [
                [
                    200.61,
                    284.8897637795277,
                    566.94,
                    307.3697637795277
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "MetalLinedFlangeConnectionMaterial": {
        "parameter_properties": {
            "value": "stainless steel",
            "unit": null,
            "bboxes": [
                [
                    200.61,
                    329.93976377952765,
                    566.94,
                    352.41976377952767
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "RubberLinedFlangeConnectionMaterial": {
        "parameter_properties": {
            "value": "CGB",
            "unit": null,
            "bboxes": [
                [
                    200.61,
                    329.93976377952765,
                    566.94,
                    352.41976377952767
                ]
            ],
            "pageIndexes": [
                2
            ]
        }
    },
    "ADpvcALSFlangeConnectionStandard": {
        "parameter_properties": {
            "value": "EN 1092-1 DN80 PN10 ASME B16.5 Class 150 NPS 3 JIS B2220 10K 80A",
            "unit": null,
            "bboxes": [
                [
                    199.71,
                    50.849763779527734,
                    566.94,
                    100.34976377952773
                ]
            ],
            "pageIndexes": [
                3
            ]
        }
    },
    "ADPEDFlangeConnectionStandard": {
        "parameter_properties": {
            "value": "EN 1092-1 DN80 PN10 ASME B16.5 Class 150 NPS 3.",
            "unit": null,
            "bboxes": [
                [
                    199.71,
                    100.35976377952773,
                    566.94,
                    136.3897637795277
                ]
            ],
            "pageIndexes": [
                3
            ]
        }
    },
    "EGASMEFlangeConnectionStandard": {
        "parameter_properties": {
            "value": "ASME B16.5 Class 150 NPS 3 EN 1092–1 DN80 PN16.",
            "unit": null,
            "bboxes": [
                [
                    199.71,
                    199.35976377952773,
                    566.94,
                    235.3897637795277
                ]
            ],
            "pageIndexes": [
                3
            ]
        }
    }
}
